name = "cryptoumn"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.37"

[author]
  name = "Jacob Lindahl"
  homepage = "http://geeklaunch.net"
